### ISSUE TITLE
Feature Request: NOAA Tides and Currents Highcharts Widget

### ISSUE THREAD

**Issue by Prindle19** [steepleian/weewx-Weather34#10]
Would be great to have a tide panel in Weather34. 

The newer NOAA site actually already uses highcharts so this might not be that difficult to add. 

https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8532591 

Each station also has associated webservices (XML, JSON, etc.) for retrieving data: 

https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?product=predictions&application=NOS.COOPS.TAC.WL&begin_date=20201118&end_date=20201119&datum=MLLW&station=8532591&time_zone=lst_ldt&units=english&interval=hilo&format=json

**Comment by steepleian** [comment]
Sean,

You can set up the web service yourself.

You need to add 4 pieces of information to the [Weather34WebServices] stanza in the weewx.conf file: -

    tc_url = https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?product=predictions&application=NOS.COOPS.TAC.WL&begin_date=20201118&end_date=20201119&datum=MLLW&station=8532591&time_zone=lst_ldt&units=english&interval=hilo&format=json <https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?product=predictions&application=NOS.COOPS.TAC.WL&begin_date=20201118&end_date=20201119&datum=MLLW&station=8532591&time_zone=lst_ldt&units=english&interval=hilo&format=json>

    tc_interval = 3600

    tc_filename = /var/www/html/weewx/weather34/jsondata/tides_currents_data.txt

 and finally add tc to your services code string for example: -

services = eq.ki.pu.ds.wu.me.tc

After you have made the changes, restart WeeWX and after a few minutes the tides_currents_data.txt file should appear in the jsondata folder and thereafter will be updated every 3600 seconds.

You can then parse this file and use the result to update your Highchart.

Ian

**Comment by balloonhotair** [comment]
If you just want to add the page you can do that by adding this line to index.php in a location that you like to have the link.
<?php echo '<a alt="NOAA" title="NOAA" href="https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8532591" data-lity>&nbsp;'.$chartinfo." NOAA</a>";?>
Since it is php make sure you put in in a valid spot. Here is an example how I added it to my darksky forecast section
<?php if ($position6=='forecast3wu.php' || $position6=='forecast3wularge.php') {echo ' <a alt="weather underground forecast" title="weather underground forecast" href="outlookwu.php" data-lity>'. $chartinfo. " Daily F.cast </a>";}?>
<?php if ($position6=='forecast3ds.php' || ($dshourly=='yes' && $apikey!= '11111111111111' && ($position6=='forecast3wu.php' || $position6=='forecast3wularge.php'))) {echo '<a alt="Hourly Forecast" title="Hourly Forecast" href="forecastdshour.php" data-lity>&nbsp;'. $chartinfo. " Hourly F.cast</a>";}?></span>
<?php if ($position6=='forecast3ds.php' || ($dshourly=='yes' && $apikey!= '11111111111111' && ($position6=='forecast3wu.php' || $position6=='forecast3wularge.php'))) {echo '<a alt="Alerts" title="Alerts" href="darkskyalerts.php" data-lity>&nbsp;'. $chartinfo. " Alerts</a>";}?>
**<?php echo '<a alt="NOAA" title="NOAA" href="https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8532591" data-lity>&nbsp;'.$chartinfo." NOAA</a>";?>**</span>

**Comment by balloonhotair** [comment]
Github messed up the example. Here is it again.
<?php if ($position6=='forecast3wu.php' || $position6=='forecast3wularge.php') {echo ' <a alt="weather underground forecast" title="weather underground forecast" href="outlookwu.php" data-lity>'. $chartinfo. " Daily F.cast </a>";}?>
<?php if ($position6=='forecast3ds.php' || ($dshourly=='yes' && $apikey!= '11111111111111' && ($position6=='forecast3wu.php' || $position6=='forecast3wularge.php'))) {echo '<a alt="Hourly Forecast" title="Hourly Forecast" href="forecastdshour.php" data-lity>&nbsp;'. $chartinfo. " Hourly F.cast</a>";}?></span>
<?php if ($position6=='forecast3ds.php' || ($dshourly=='yes' && $apikey!= '11111111111111' && ($position6=='forecast3wu.php' || $position6=='forecast3wularge.php'))) {echo '<a alt="Alerts" title="Alerts" href="darkskyalerts.php" data-lity>&nbsp;'. $chartinfo. " Alerts</a>";}?>
<?php echo '<a alt="NOAA" title="NOAA" href="https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8532591" data-lity>&nbsp;'.$chartinfo." NOAA</a>";?></span>

**Comment by balloonhotair** [comment]
If you just want to add the page you can do that by adding this line to index.php in a location that you like to have the link.
`<?php echo '<a alt="NOAA" title="NOAA" href="https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8532591" data-lity>&nbsp;'.$chartinfo." NOAA</a>";?>`
Since it is php make sure you put in in a valid spot. Here is an example how I added it to my darksky forecast section

**Comment by Prindle19** [comment]
Thanks - i'm going to mess around with the highcharts a bit, but since the dates need to be set dynamically I just made a noaa.php to serve out of the weather34 directory to call from the weewx.conf 

`<?php

$station = (isset($_GET['station'])) ? $_GET['station'] : false;

$today = new DateTime('today');
$today = $today->format('Ymd');

$tomorrow = new DateTime('tomorrow');
$tomorrow = $tomorrow->format('Ymd');
$url = "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?product=predictions&application=NOS.COOPS.TAC.WL&begin_date={$today}&end_date=${tomorrow}&datum=MLLW&station={$station}&time_zone=lst_ldt&units=english&interval=hilo&format=json";

header('Content-Type: application/json');      
$string = file_get_contents($url, false);
echo $string;`

that way I can just call it as http://localhost/weewx/weather34/noaa.php?station=8532591
