### ISSUE TITLE
Value of StdReport.RSYNC.enable is ignored

### ISSUE THREAD

**Issue by Nkawu** [steepleian/weewx-Weather34#131]
Thanks for the great work on the skin!

In a case where rsync isn't used at all, I notice the value of `StdReport.RSYNC.enable` in `weewx.conf` is ignored and `weather34.py` still attempts to rsync data leading to lots of errors.

I haven't looked at the code enough to find this for myself, but was wondering:

- Does Weather34 even work without running rsync?
- Does the data created in `/tmp/weather34` always get copied to `/home/weewx/public_html/weather34`?

Maybe a check something like this would work to avoid the errors?
```python
if self.config_dict['StdReport']['RSYNC'].get('enable', False):
    do_rsync_transfer(....
```

**Comment by balloonhotair** [comment]
weather34 only uses rsync when remote web servers are enabled in the weather34 realtime section otherwise weather34 does not use rsync. Need to see error logs to understand what is going on. Other than the rsync user name and port the weather34 uses no other fields since this section is for weewx rsync.  With the exception of one user that we know of no one uses rsync in weather34.

**Comment by Nkawu** [comment]
Thanks, sounds like I don't need to bother then. In `Weather34RealTime`, do I leave most of the parameters blank (weewx_port, realtime_path_only, webserver_address, weewxserver_address, weewx_file_transfer)?

The `do_rsync_transfer` function was definitely being called very often by `Weather34RealTime.write_data`. I notice the error was caused by me not having `StdReport.RSYNC.port` defined, leading to a `int(None)` error somewhere (can't find it now in the code).

**Comment by balloonhotair** [comment]
Unless you are doing remote webservers leave the fields blank or moving location of realtime.txt file.

**Comment by balloonhotair** [comment]
Closing not an issue.
