### ISSUE TITLE
Graph Length/Time Do Not Match

### ISSUE THREAD

**Issue by gary-hammer** [steepleian/weewx-Weather34#15]
When clicking on Yearly, Monthly, Weekly below any of the data panels (Temp, Wind, Rain, etc) the graph is not what was offered.
Click Yearly, all data is graphed with no 1 year option. On Temp, click Weekly, you get a 24 Hr graph with no 7 day option.

All the data panels and associated graphs have the same issue.

https://weather.ghammer.net to see what I'm posting about if these are correct for you.

**Comment by balloonhotair** [comment]
So with weekly the All option is 7 days and by design weekly chooses the current day
Yearly is not so, since users wanted to see All their data so yearly got replace by all, but now it looks like Year should have stayed and All should have been added. So I will add a Year choice to the range selector.

**Comment by balloonhotair** [comment]
Added 1yr option to the ranger selector for year and radial charts in the dev branch.

**Comment by steepleian** [comment]
Will be featured in the next version of weewx-Weather34
