### ISSUE TITLE
WU Forecast always blank

### ISSUE THREAD

**Issue by dotJson** [steepleian/weewx-Weather34#18]
Working Weewx 4.1.1 install, properly rsync-ing to remote web server.  No matter what I try the WU forecast data never populates.  I have installed the Weewx Forecast extension (https://github.com/chaunceygardiner/weewx-forecast) and debug shows it writing to database, and the /weewx/forecast directory is rsync-ing to the web server (though not in /weewx/weather34/forecast if that matters).  I'm not even sure if the extension (Chauncey Gardiner's) is supposed to feed the forecast3wu.php/forecast3wularge.php file or not.  The /jsondata/wuforecast.txt is missing which I thought was a piece of this puzzle, too.

**Comment by steepleian** [comment]
Jason,Weather34 does not use the weewx-forecast extension or the chaunceygardiner fork and never has done. This is all facilitated by the settings page select from the menu. Which version of Weather34 are you using? If you are using the current live version wether34.py has its own built-in webserver function which includes utilising WU forecast data via it API.  You need to make sure these sections on settings page are completed: -And   Sent from Mail for Windows 10 From: Jason YoungSent: 11 September 2020 18:17To: steepleian/weewx-Weather34Cc: SubscribedSubject: [steepleian/weewx-Weather34] WU Forecast always blank (#18) Working Weewx 4.1.1 install, properly rsync-ing to remote web server. No matter what I try the WU forecast data never populates. I have installed the Weewx Forecast extension (https://github.com/chaunceygardiner/weewx-forecast) and debug shows it writing to database, and the /weewx/forecast directory is rsync-ing to the web server (though not in /weewx/weather34/forecast if that matters). I'm not even sure if the extension (Chauncey Gardiner's) is supposed to feed the forecast3wu.php/forecast3wularge.php file or not. The /jsondata/wuforecast.txt is missing which I thought was a piece of this puzzle, too.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dotJson** [comment]
OK.  That makes sense.  I do have the settings set up for WU updates.  I'm running W34-HC-IMJD-2.0.0 on Weewx 4.1.1

What can I include here that will help?

**Comment by steepleian** [comment]
Let me have your coordinates, you can email me directly just to check they
are working for your location with my own api token and we will take it
from there.

**Comment by dotJson** [comment]
Thanks for your help on this.  Where do I email the coords to?

**Comment by steepleian** [comment]
steepleian@gmail.com

**Comment by steepleian** [comment]
Adopted weewcron method
