### ISSUE TITLE
Highcharts - Selecting start date of september in 1 year view results in 36h view starting in April

### ISSUE THREAD

**Issue by m90att** [steepleian/weewx-Weather34#20]
I'm selecting a start date of 14 Sep and it's displaying an April date.  

[Highcharts.zip](https://github.com/steepleian/weewx-Weather34/files/5223084/Highcharts.zip)

_Originally posted by @m90att in https://github.com/steepleian/weewx-Weather34/issues/17#issuecomment-692519539_

**Comment by balloonhotair** [comment]
So this is by design. Since you are asking for a date is right at the right edge of what data is in the database and the system tries to get three days worth which puts the date into the future it fails, and when getting any date results in a failure then the first good date in the database is returned. This is the best way to let you a date fail and still keep the chart active. So if you are getting a date that is in 1 week of the current date best to use the weekly span and not the yearly span

**Comment by m90att** [comment]
I'm sorry, I don't follow.  I'm selecting a start date that is a couple of days before the default yearly plot that is displayed by default when the popup opens.  I don't understand how this can be on the right edge of what data is in the database as it is data before the default span.  The system should be trying to find 1 years worth of data only from 2-3 days before the default date span.  I'm afraid I'm still struggling to get a view of historical yearly data.

**Comment by balloonhotair** [comment]
Hi,
It does not work the way you want it to. The current system only gives you one year from the current date to the past. Also when you click on a date you just get that date and a day on either side of it. Same with the calendar. The calendar is a very basic date chooser and has no knowledge of valid dates. If midnight of the chosen date is not found in the database the system will look for 1500 minutes forward to find a date. If no date is found then the first good date is displayed. You can pretty much treat seeing the first date in the database being displayed as an error message. The template really has very little to say on what happens it just executes a weewx program giving it a timestamp and waits to see what happens.
