### ISSUE TITLE
mb_http_input error

### ISSUE THREAD

**Issue by Leosirth** [steepleian/weewx-Weather34#3]
Hi,

I had to change the following in "common.php" to make the skin working:

`mb_http_input('UTF-8');`

to

`mb_http_input('G');`

Based on PHP documentation:

https://www.php.net/manual/en/function.mb-http-input.php

UTF-8 is not a valid type, it should be one of:

`"G" for GET, "P" for POST, "C" for COOKIE, "S" for string, "L" for list, and "I" for the whole list`

I would like to fix this on the code.
Is this a fixed value or is calculated at some point? I could not spot this in the code or installation script.

I would assume that is not fixed for all, otherwise I don't understand how this could work for you.
Another reason could be the PHP version, I'm on PHP 8.0.1 but the only change logged for this function is:

Version | Description
-- | --
8.0.0 | type is nullable now.

That doesn't looks relevant.

**Comment by steepleian** [comment]
Francesco
You may have saved me a lot of work. I had a quick look at PHP8.0 compatibility which you obviously found did not work. I have not had a chance since to look deeper into the problem. If that is the only change that needs to be made, that is an excellent catch. I will check it out on my test server.
Thank you
Ian

**Comment by steepleian** [comment]
Making that change did not work for me, just a white screen and nothing in the browser console log. Obviously something missing in my PHP8.0 installation. What device and OS are you running the skin on?

**Comment by Leosirth** [comment]
Hi Ian,

glad to help.
Indeed I had to make another adjustment for which I was investigating if related to my data or not.

in **w34CombinedData.php**, I had to change the following lines:

```
$weather["maxtemptime"]        = date($timeFormatShort, $weewxapi[27]);
$weather["lowtemptime"]        = date($timeFormatShort, $weewxapi[29]);
$weather["maxwindtime"]        = date($timeFormatShort, $weewxapi[31]);
$weather["maxgusttime"]        = date($timeFormatShort, $weewxapi[33]);
```

into:

```
$weather["maxtemptime"]        = $weewxapi[27];
$weather["lowtemptime"]        = $weewxapi[29];
$weather["maxwindtime"]        = $weewxapi[31];
$weather["maxgusttime"]        = $weewxapi[33];
```

This because in my **archivedata.php** they are already only time:

```
$weewxapi[27] = "11:56";
$weewxapi[29] = "06:12";
$weewxapi[31] = "08:40";  
$weewxapi[33] = "09:05";
```
And PHP complain that the date wants a full timestamp as argument.

The fix for me is only a workaround while checking more deeply.
I don't know if it's my station that only send the time instead of the full timestamp.
A more robust implementation should check if this is only a time, in case convert to a valid timestamp and convert back to the timeFormat configured.

Do you have the same situation?

**Comment by steepleian** [comment]
My archivedata is the same but that fix did not work for me either.

**Comment by Leosirth** [comment]
Do you have the **Sockets Extension** enabled?

My setup is not very standard, I have dockerized weewx.
PHP is on a different container and the webserver is nginx on a third container.

**Comment by steepleian** [comment]
Yes socket extensions enabled, I am running PiOS Lite on a RaspberryPi4, with Apache2. It feels to be maybe a library is missing somewhere. php -m gives me this: - [PHP Modules]bcmathcalendarCorectypecurldatedomexifFFIfileinfofilterftpgdgettexthashiconvintljsonlibxmlmbstringmysqlimysqlndopensslpcntlpcrePDOpdo_mysqlpdo_sqlitePharposixreadlineReflectionsessionshmopSimpleXMLsocketssodiumSPLsqlite3standardsysvmsgsysvsemsysvshmtokenizerxmlxmlreaderxmlwriterxslZend OPcachezipzlib [Zend Modules]Zend OPcache Sent from Mail for Windows 10 From: FrancescoSent: 28 January 2021 13:39To: steepleian/weewx-Weather34Cc: Ian Millard; CommentSubject: Re: [steepleian/weewx-Weather34] mb_http_input error (#3) Do you have the Sockets Extension enabled?My setup is not very standard, I have dockerized weewx.PHP is on a different container and the webserver is nginx on a third container.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Leosirth** [comment]
Change

`error_reporting(0);`

on line 11 of **w34CombinedData.php** to:

`error_reporting(-1);`

This will give you some hint on what is failing.

**Comment by steepleian** [comment]
Error seems to be related to the original error you pointed out PHP Fatal error:  Uncaught ValueError: mb_internal_encoding(): Argument #1 ($encoding) must be a valid encoding, "G" given in /var/www/html/weewx/weather34/common.php:mb_internal_encoding()\n#1 /var/www/html/weewx/weather34/index.php(2): include_once('...')\n#2 {main}\n  thrown in /var/www/html/weewx/weather34/common.php on line 5' Sent from Mail for Windows 10 From: FrancescoSent: 28 January 2021 14:09To: steepleian/weewx-Weather34Cc: Ian Millard; CommentSubject: Re: [steepleian/weewx-Weather34] mb_http_input error (#3) Changeerror_reporting(0);on line 11 of w34CombinedData.php to:error_reporting(-1);This will give you some hint on what is failing.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Leosirth** [comment]
You changed **mb_internal_encoding** instead of **mb_http_input**, this is what I have:

```
mb_internal_encoding('UTF-8');
mb_http_output('UTF-8');
mb_http_input('G');
mb_language('uni');
mb_regex_encoding('UTF-8');
ob_start('mb_output_handler');
```

**Comment by steepleian** [comment]
Sorry my bad. That fixed thanks. I will tidy things up and update the repository to announce PHP 8 compatibility.Thank you for picking the issue up. One less job on my to do list.Ian Sent from Mail for Windows 10 From: FrancescoSent: 28 January 2021 16:15To: steepleian/weewx-Weather34Cc: Ian Millard; CommentSubject: Re: [steepleian/weewx-Weather34] mb_http_input error (#3) You changed mb_internal_encoding instead of mb_http_input, this is what I have:mb_internal_encoding('UTF-8');mb_http_output('UTF-8');mb_http_input('G');mb_language('uni');mb_regex_encoding('UTF-8');ob_start('mb_output_handler');—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by steepleian** [comment]
Fix applied to common.php and w34CombinedData.php to resolve PHP 8 compatibility issue.

Thanks to Francesco for providing the solution
