### ISSUE TITLE
Remove/Replace Darksky API

### ISSUE THREAD

**Issue by Rayvenhaus** [steepleian/weewx-Weather34#3]
Darksky API is no longer available since the assimilation of Darksky by The Apple Collective and the abrupt shutdown of the API, embedded services, and Apps.

We need to replace it with either ClimaCell, which does have a free API, albeit a rate-limited one ( 100calls/hr or 1000/day max) or something similar.

**Comment by steepleian** [comment]
Just for clarification, are you one of the unlucky people who did not have an API key before the Apple take over? The reason I ask is that the API is still working for me and my Apps also work. I know this will change later this year for existing API key holders, but was not expecting just now.

The situation is that Weather Underground (for all its tempermental past behaviour) will continue to be the forecasting mainstay for the skin. I may regret saying this but it has been very stable for me in the past few months, have the owners finally got its act together I wonder?

DarkSky does provide the most detailed hourly report. I have looked at several including ClimaCell (a 1000 calls a day seems plenty me given that its only necessary to refresh once an hour at the most) however I am yet to find a perfect match replacement for the DarkSky hourly detail. Some APIs do have the detail I am looking for in the weather description, but as free text data rather then specific data classes. The parsing of free text dates then makes for complicated and messy parsing techniques.

DarkSky will be removed when it ceases to function and in the meantime I will continue my research for a replacement. I am also open to offers from anyone to assit me in this process as I now have to limit my screen time due to persistent eye strain.

**Comment by steepleian** [comment]
I have just been having another look at ClimaCell. It should actually be possible to be possible to buils an endpoint that mimics DarkSky. Food for thought, but I have just signed up anyway.

**Comment by Rayvenhaus** [comment]
I am more than happy to assist in this. I've just rebuilt my server, fresh install of WeeWX on Raspberry Pi 4, WeeWX 4.3.0, Ecowitt GW1000 with the following sensors that I want to fully integrate into the skin:

GW1001 | Wi-Fi Weather Station with Solar Powered   7-in-1 Outdoor Sensor Array, Weather App & Weather Server | 1
RS-00001 | Ecowitt Temperature and Humidity Solar   Radiation Shield for WH32/WH31 Sensor | 1
WH0281 | Wireless Indoor Outdoor Thermometer Digital   Temperature Monitor | 1
WH40 | Wireless Self-Emptying Rain Collector   Rainfall Sensor | 1
WH41 | PM2.5 Air Quality Sensor Monitor Outdoor | 1
WH43 | PM2.5 Air Quality Sensor for Indoor Use | 1
WH51 | Wireless Soil Moisture Sensor Max 8 Channels   Soil Humidity Tester | 4
WH57 | Wireless Lightning Detection Sensor with   Email Alert | 1

**Comment by steepleian** [comment]
Snap. I use GW1000 with my WeeWX setup. I have everything you have apart soil moisture sensor (we are not short of rain here in Pommie Land). I have working skin modules for the AQI devices and also for an SDS011 particle sensor which is used in the Lufdaten project). I also have a Davis rig with Meteobridge but I find that very constraining but its a useful for comparisson/callibration. 

The Weather34 skin now has web services built into the Python code itself. This development version will soon be rolled out as the next live version (4.0.0). The web services are now integrated into the Python code courtesy of my wizard collaborator Jerry. It is now even easier to set up endless web services to connect to APIs. All we need to know is the API URL. From what I can see the user has to create the URL themself based on the individual requirements. Is this something you could work out? If the data retrieved is as close as possible to DarkSky, after the jsondata is parsed, it becomes a simple drop-in for the existing code.

**Comment by Rayvenhaus** [comment]
Still trying to get everything integrated with the GW1000 Driver, WeeWX, and Weather34 skin.  If you've got any pointers, please share.

As far as working on the programming side here, I'd be honored to. Please feel free to reach out to me via email and we can collaborate there.  I've got a few decades of PHP and web design under my belt.

I'll get started looking at ClimaCell today.

**Comment by steepleian** [comment]
Yes that’s great you can email me directly on steepleian@gmail.com and we can discuss in more detail without cluttering up the issue log.
Regards,
Ian

**Comment by steepleian** [comment]
> Still trying to get everything integrated with the GW1000 Driver, WeeWX, and Weather34 skin. If you've got any pointers, please share.
> 
> As far as working on the programming side here, I'd be honored to. Please feel free to reach out to me via email and we can collaborate there. I've got a few decades of PHP and web design under my belt.
> 
> I'll get started looking at ClimaCell today.

Can you send me your email address to steepleian@gmail.com
Thanks,
Ian

**Comment by Rayvenhaus** [comment]
Done
