### ISSUE TITLE
Installation fails with error around import configobj

### ISSUE THREAD

**Issue by iamdadzilla** [steepleian/weewx-Weather34#31]
Trying to install into Weewx 4.0 running on Raspbian, all freshly installed. Python 2.7.16. Here's the error:

`Traceback (most recent call last):
  File "w34_installer.py", line 2, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj
`

I used the first recommended installation procedure:
`sudo git clone https://github.com/steepleian/weewx-Weather34.git`
`cd weewx-Weather34`
`sudo python w34_installer.py`

Thanks for any help!

**Comment by steepleian** [comment]
Hi,

You need to install configob for Python2

sudo apt install python-configobj

If you find any other objects missing, have a look at the setup.py install instructions here http://www.weewx.com/docs/setup.htm <http://www.weewx.com/docs/setup.htm>

As you are using Python 2.7 rather than 3.6 just remove 3 from python as in the solution above.

Ian

**Comment by jmontamat** [comment]
Tnx.
Josep.

**Comment by iamdadzilla** [comment]
That did it. Thanks!

**Comment by steepleian** [comment]
Ok glad its working now. Enjoy.
