### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Rayvenhaus** [steepleian/weewx-Weather34#5]
Fresh installation of Raspberry PI (Buster)
Fresh Install of WeeWX (4.3.0) using the setup.py method
Base LAMP (Apache2, MariaDB, PHP) installed
All pre-req's installed.

Installed Weather34 V4.0.0 Dev and selected option #3, setup.py method and setup completed successfully, however, files are not installed in the correct directories. WeeWX places everything in the /home/weewx directory and generated web files in the /home/weewx/public_html directory yet the installation process for Weather34 placed it's web files in /var/www/html/weewx/weather34

setup_py.conf is hardcoded to use /var/www/html/weewx/weather34 which is incorrect and leads to, what appears to be, and completely failed installation, which it's not technically, it's just in the wrong location.

_{"zip_file":"",
"copy_paths":"/home/weewx/bin/user/,user,/home/weewx/skins/,skins,/var/www/html/weewx/weather34/,www",
"weewx_config_file":"/home/weewx/weewx.conf",
"www_path":"/var/www/html/weewx/weather34/",
"over_write":"False",
"delete_extracted_files":"False",
"extract_to_path":".",
"uid_gid":"www-data,www-data",
"config_entries0":'''StdReport=
                        'Weather34Report': {
                        'skin': 'Weather34',
                        'HTML_ROOT': '/var/www/html/weewx/weather34/',_

**Comment by balloonhotair** [comment]
Hi,
Please do not open issues on the dev branch, since this repository is always in a state of flux and there are many untested versions of code in this repository. If there is an issue with the master branch then please open an issue on that master branch. Issues open here may not get seen or looked at that is why there is warning about using this branch. The last item that gets check before a release is the install.
Thanks
