### ISSUE TITLE
wrong path

### ISSUE THREAD

**Issue by ivannunyadambiz** [steepleian/weewx-Weather34#77]
my weewx runs in /var/www/html, and even after making sure /etc/weewx/weewx.conf does not list /var/www/html/weewx even once, weather34 gets installed in /var/www/html/weewx/weather34 instead of in /var/www/html/weather34

**Comment by balloonhotair** [comment]
Since is a non-standard path location you need to edit setup_py.conf and put the correct paths for the following fields.
Double, triple check that all characters besides the paths match what is listed below.

"copy_paths":"/home/weewx/bin/user/,user,/home/weewx/skins/,skins,/var/www/html/weewx/weather34/,www",
"weewx_config_file":"/home/weewx/weewx.conf",
"www_path":"/var/www/html/weewx/weather34/",

**Comment by steepleian** [comment]
So in fact as your are using a packaged install of WeeWX, you should edit the lines 2, 3 and 4 in packaged.conf file to the following paths for your installation: -

"copy_paths":"/usr/share/weewx/user/,user,/etc/weewx/skins/,skins,/var/www/html/weather34/,www",
"weewx_config_file":"/etc/weewx/weewx.conf",
"www_path":"/var/www/html/weather34/",

**Comment by ivannunyadambiz** [comment]
well... thanks for the replies
just as i figured it out. indeed the packaged.conf file...
