### ISSUE TITLE
Unable to install the Weather34 using wee_extensions due to filename error

### ISSUE THREAD

**Issue by athua** [steepleian/weewx-Weather34#9]
When trying to install the Weather34 extension using wee_extension, it fails with an error that it is unable to find easyW34skinSsetup.php.

I found the problems and it is due to a miss spelling of the filename in install.py:

The line is:

'skins/Weather34/easyW34skinSsetup.php',

but I think it should be:

'skins/Weather34/easyW34skinSetup.php',

**Comment by steepleian** [comment]
Solved see this commit
https://github.com/steepleian/weewx-Weather34/commit/5d1d44ad3dfb78b320cc9319eb4352d0472078b5

**Comment by athua** [comment]
Hi Ian,

Thanks for correcting it so quickly. I thought I might bring the typo to
your attention to save others time when trying to install Weather34 for
WeeWX. It took me a while to figure out why the extension wasn't installing
and thought it was an issue with my WeeWX installation until I noticed the
spelling error in the filename.

I have also just noticed a number of other minor issues:
1. 'weewxcron.php' is missing from install.py so its not getting copied
when installing the extension.
2. In 'weewxcron.php', the Weather Underground data is saving to
'jsondata/wuweatherupdate.txt' but the 'forecast3wu.php' is looking for
data in 'jsondata/wuforecast.txt' so no data is appearing in the Forecast.
3. 'weewxcron.php' is missing the darksky code section that was in the
previous version (w34skin). When I added the section back in, the Darksky
data started populating.
4. 'menu.php' has the file name for the settings page as
'easyW34skinsetup.php' when it should be 'easyW34skinSetup.php'.

Regards,
Augustus.

**Comment by steepleian** [comment]
Hi Augustus,

Thanks for alerting me to the error. I never use the settings from the menu as I edit settings1.php directly.

The other things you mention. They are no longer required. I am in the process of updating the documentation, you beat me to it!

All the web service APIs are now built into weather34.py. The weewxcron method was giving problems to people in certain parts of the world. The new method is much more robust and will ensure that you will not exceed any limits set by the API services due to heavy website traffic).

If you open your settings page, there are extra items. Firstly you need to set your path to your jsondata folder. This is the next field to where you set your w34realtime.txt location.
This would normally be /[your-path]/weewx/weather34/jsondata (mine for instance is /var/www/html/weewx/weather34/jsondata)

Under the Purple Air section, you will find an AQI setting which you can use and an alternative to Purple Air.

There is also a new section just above the save configuration button at the bottom where you set the timings for the services in seconds. (You can disable Weather Underground and Purple Air by setting to 0, the others are always required so there is no 0 setting). 

The is part of a much larger update that I am working on at the moment which will improve performance all round. 

Regards,
Ian
