### ISSUE TITLE
Apparent Temp / Windchill not showing (but do exist)

### ISSUE THREAD

**Issue by Prindle19** [steepleian/weewx-Weather34#9]
ALMOST have everything working properly (fantastic application on top of weewx, btw! 

Something appears to be off with the Apparent Temp and Windchill in temperature.php (Circled in Red below) 

<img width="299" alt="temp1" src="https://user-images.githubusercontent.com/1731718/99571647-928b2c80-29a1-11eb-8f18-1a682a196cc8.png">

Also, why is the temperature shown in Celsius (circled in Yellow above) when I have US units set? 

The Apparent Temperature and Windchill temperature data does appear to exist, you can see them in the highcharts for Feels 

<img width="770" alt="temp2" src="https://user-images.githubusercontent.com/1731718/99571811-cc5c3300-29a1-11eb-8345-e93d1f19d772.png">

**Comment by balloonhotair** [comment]
Hi,
Yellow circle is normal. The template always shows the alt temp from the large temp display.
The missing fields are realtime values from weewx calculations. To figure out why they are not showing the following files need to be posted to this issue. Since you are the only one reporting this.
1) archivedData.php
2) The browser error console log to see if there are any javascript errors.
3) syslog to see if there are any weewx errors.
You can just drag and drop the files into this issue.

**Comment by Prindle19** [comment]
[weewx.zip](https://github.com/steepleian/weewx-Weather34/files/5570150/weewx.zip)

**Comment by Prindle19** [comment]
Thanks for taking a look - attached the 3 of them.

**Comment by balloonhotair** [comment]
Nothing showed up in the logs.
Can you post w34realtime.txt
Does your website have an external URL?

**Comment by Prindle19** [comment]
No, haven't hardened this server to the point i'm comfortable exposing it yet! 

[w34realtime.txt](https://github.com/steepleian/weewx-Weather34/files/5570201/w34realtime.txt)

**Comment by balloonhotair** [comment]
So the missing fields are null in the realtime file which means that there was no data for these fields when the weather34.py sampled the loop data. Also since you have graphs with data means the data is getting into your database.  My guess would be that you have the weather34.py service running to early within the weewx stack. Best to post the part of the weewx.conf file that contain all the services to see if the order is incorrect. This issue is not in the template code and not in weewx code so the only part left is configuration. Since these values are calculated by weewx make sure they are software generated in the weewx.conf also.

**Comment by steepleian** [comment]
Sean,

Try this modified archivedata.php.tmpl file. It livers in the skins/weather34/serverdata folder

**Comment by balloonhotair** [comment]
Just to note here windchill and apparent are realtime (loop data) not archive data.

**Comment by steepleian** [comment]
Agreed.

**Comment by Prindle19** [comment]
[weewxconf.zip](https://github.com/steepleian/weewx-Weather34/files/5574380/weewxconf.zip)

Copied over the new .tmpl and restarted but still the same

**Comment by steepleian** [comment]
We need to see your archivedata.php file again. The replacement template
should have generated the missing data from the average of your last
archive cycle.

**Comment by steepleian** [comment]
Also is the file actually updating at the end of every archive cycle -
check the time stamp on the file.

**Comment by Prindle19** [comment]
[archivedata.zip](https://github.com/steepleian/weewx-Weather34/files/5575065/archivedata.zip)

Looks like its updated since the template was updated.

**Comment by steepleian** [comment]
So the data is now in the archive file, therefore it should appear on the
dashboard. Have you tried emptying your browser cache? It is not always
sufficient to refresh the screen.

**Comment by balloonhotair** [comment]
This does not work unless you update w34CombinedData.php with the new locations since template gets to values from the realtime file not the archive data file. Also this approach means the updates will be at archive time deltas and not loop deltas, and there is still the issue of why this is not working in the first place.

**Comment by Prindle19** [comment]
Yeah, even from different PCs (including ones that never visited the site), I'm still not getting the values

**Comment by balloonhotair** [comment]
Please make the following changes to w34CombinedData.php and still use the tmpl file Ian states above.
 If this change works I can explain what I think is going on.

change
        $weather["apptemp"]            = $weewxrt[54];
to
       $weather["apptemp"]            = $weewxapi[41];

change
        $weather["windchill"]          = $weewxrt[24];
to
       $weather["windchill"]          = $weewxapi[24];

**Comment by Prindle19** [comment]
Yep, that worked.

**Comment by balloonhotair** [comment]
Great, So here is what I suspect. Weewx is not calculating the missing data for loop packets anymore. Now this can be a result of the recent changes done by weewx to these calculations for version  4.2+ or the sensor is not supplying the necessary data to weewx to do the calculation when creating loop packet data. This is a first for me so it is my best guess. So now the template has to return these values in archivedData.php and w34Combined.php will have to see if the loop data is missing check for archived packet for data. The down side to this is these values are now updated at archive packet intervals which are longer than loop packet intervals.

**Comment by steepleian** [comment]
I have been running the modified archivedata.php on a test server for a few
days now, comparing with the standard version. The good news is that the
loop version and archive version are almost identical in what is displayed.
Obviously a long archive cycle and a rapid change in conditions would
potentially show a divergence in what is displayed. For the record, my
archive cycle is 5min and I am running 4.2 (calculated loop packet data is
working). I would be interested to know which weather station hardware you
are using and your archive cycle time. Jerry mentioned in an earlier post
that the issue is related to WeeWX itself rather than the template. It
might also be useful to post a general question on the WeeWX user group to
see if somebody else had a similar issue.
Ian

**Comment by balloonhotair** [comment]
Ian I have the changes to w34CombinedData.php ready to submit that does the checks so when I see your changes for the tmpl I will submit mine.

**Comment by steepleian** [comment]
Hi Jerry,
The alternative archivedata.php.tmpl is exactly the same as the one I attached for Sean. It would be easier to have a look at your changes to w34CombinedData.php so I can modify archivedata.php.tmpl to match. I assume you are doing a check for calculated loop data and if not present dropping through to archive data so will need a parallel set of variables.
Cheers,Ian

**Comment by steepleian** [comment]
Fix applied to use archive packet if heatindex loop packet is empty. Update w34CombinedData.php and archivedata.php.tmpl
